# -*- coding: utf-8 -*-
"""EMNASKRT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qVMoxk9fOMi_F5hLqwrKpFUlrRHz_DWs
"""

!pip install -q -U transformers peft accelerate bitsandbytes datasets trl

import pandas as pd
import json
import os
import numpy as np

path = '/content/data'
output_path = '/content/converted_json'
os.makedirs(output_path, exist_ok=True)

# CO2 emission factor for natural gas (kg CO2 per Nm3)
CO2_FACTOR = 2.04

files = [f for f in os.listdir(path) if f.endswith('.xlsx')]

for filename in files:
    xlsx_path = os.path.join(path, filename)
    try:
        df_raw = pd.read_excel(xlsx_path, header=None)
        date_row  = df_raw.iloc[9]
        time_row  = df_raw.iloc[10]
        data_rows = df_raw.iloc[11:]

        # Build time-series records
        records = []
        for col in df_raw.columns[4:]:
            date_val = str(date_row[col]).strip()
            time_val = str(time_row[col]).strip()
            if date_val in ('nan','None','') or time_val in ('nan','None',''):
                continue
            record = {"date": date_val, "heure": time_val}
            for _, row in data_rows.iterrows():
                cat    = str(row[0]).strip() if pd.notna(row[0]) else ""
                metric = str(row[1]).strip() if pd.notna(row[1]) else ""
                val    = row[col]
                if metric in ('nan','None','') or pd.isna(val):
                    continue
                key = f"{cat} - {metric}" if cat and cat != 'nan' else metric
                record[key] = val
            if len(record) > 2:
                records.append(record)

        if len(records) < 6:
            print(f"⚠️ {filename}: not enough records, skipping")
            continue

        training_examples = []

        for i, rec in enumerate(records):
            gas  = rec.get('Consommation gaz - Consommation du gaz naturel moteur en Nm3 (Volume)')
            prev_gas = records[i-1].get('Consommation gaz - Consommation du gaz naturel moteur en Nm3 (Volume)') if i > 0 else None
            power    = rec.get('Energie Moteur - Puissance électrique Brute en KW')
            eff_e    = rec.get('Rendement - Rendement Electrique %')
            eff_t    = rec.get('Rendement Thermique %')
            eff_tot  = rec.get('Rendement Total %')
            kwh      = rec.get("Energie éléctrique au borne de l'alternateur en KWh")
            rpm      = rec.get('Vitesse en rpm')
            voltage  = rec.get('Voltage en V')

            # ── TASK 1: CO2 Estimation ──
            if gas is not None and prev_gas is not None:
                try:
                    delta_gas = float(gas) - float(prev_gas)
                    if delta_gas >= 0:
                        co2_kg = round(delta_gas * CO2_FACTOR, 2)
                        input_data = {
                            "date": rec["date"], "heure": rec["heure"],
                            "gas_nm3_cumulative": float(gas),
                            "gas_nm3_delta": round(delta_gas, 2),
                            "power_kw": float(power) if power else None,
                            "efficiency_electric_pct": float(eff_e) if eff_e else None,
                            "efficiency_total_pct": float(eff_tot) if eff_tot else None,
                        }
                        output_data = {
                            "task": "co2_estimation",
                            "timestamp": f"{rec['date']} {rec['heure']}",
                            "co2_kg": co2_kg,
                            "gas_consumed_nm3": round(delta_gas, 2),
                            "emission_factor_kg_per_nm3": CO2_FACTOR,
                            "electrical_output_kw": float(power) if power else None,
                            "efficiency_electric_pct": float(eff_e) if eff_e else None,
                            "efficiency_total_pct": float(eff_tot) if eff_tot else None,
                            "status": "normal" if delta_gas < 500 else "high_consumption"
                        }
                        training_examples.append({
                            "text": f"<|im_start|>user\nEstimate CO2 emissions for this reading:\n{json.dumps(input_data, ensure_ascii=False)}<|im_end|>\n<|im_start|>assistant\n{json.dumps(output_data, ensure_ascii=False)}<|im_end|>"
                        })
                except:
                    pass

            # ── TASK 2: Forecasting (uses 5-step window) ──
            if i >= 5:
                window = records[i-5:i]
                kwh_vals = []
                for w in window:
                    v = w.get("Energie Moteur - Puissance électrique Brute en KW")
                    if v is not None:
                        try: kwh_vals.append(float(v))
                        except: pass

                if len(kwh_vals) == 5:
                    trend_delta = kwh_vals[-1] - kwh_vals[0]
                    trend_label = "increasing" if trend_delta > 10 else "decreasing" if trend_delta < -10 else "stable"
                    predicted   = round(kwh_vals[-1] + (trend_delta / 4), 2)
                    confidence  = round(1.0 - min(np.std(kwh_vals) / (abs(np.mean(kwh_vals)) + 1), 0.5), 2)

                    window_summary = [{"heure": w["heure"], "power_kw": w.get("Energie Moteur - Puissance électrique Brute en KW")} for w in window]
                    output_forecast = {
                        "task": "energy_forecasting",
                        "based_on_readings": 5,
                        "last_timestamp": f"{rec['date']} {rec['heure']}",
                        "predicted_next_power_kw": predicted,
                        "trend": trend_label,
                        "confidence": confidence,
                        "horizon": "next_reading"
                    }
                    training_examples.append({
                        "text": f"<|im_start|>user\nForecast the next energy value based on these 5 readings:\n{json.dumps(window_summary, ensure_ascii=False)}<|im_end|>\n<|im_start|>assistant\n{json.dumps(output_forecast, ensure_ascii=False)}<|im_end|>"
                    })

            # ── TASK 3: Anomaly Detection ──
            anomalies = []

            if rpm is not None:
                try:
                    rpm_f = float(rpm)
                    if rpm_f > 1600 or rpm_f < 1400:
                        anomalies.append({
                            "type": "out_of_range",
                            "sensor": "Vitesse en rpm",
                            "timestamp": f"{rec['date']} {rec['heure']}",
                            "value": rpm_f,
                            "expected_range": [1400, 1600],
                            "confidence": 0.95
                        })
                except: pass

            if voltage is not None:
                try:
                    v_f = float(voltage)
                    if v_f > 420 or v_f < 380:
                        anomalies.append({
                            "type": "voltage_anomaly",
                            "sensor": "Voltage en V",
                            "timestamp": f"{rec['date']} {rec['heure']}",
                            "value": v_f,
                            "expected_range": [380, 420],
                            "confidence": 0.90
                        })
                except: pass

            if i >= 3:
                prev_powers = []
                for j in range(i-3, i):
                    v = records[j].get("Energie Moteur - Puissance électrique Brute en KW")
                    if v is not None:
                        try: prev_powers.append(float(v))
                        except: pass
                if power is not None and len(prev_powers) == 3:
                    try:
                        mean_p = np.mean(prev_powers)
                        if abs(float(power) - mean_p) > 0.3 * mean_p:
                            anomalies.append({
                                "type": "spike",
                                "sensor": "Puissance électrique Brute en KW",
                                "timestamp": f"{rec['date']} {rec['heure']}",
                                "value": float(power),
                                "expected_approx": round(mean_p, 2),
                                "confidence": 0.88
                            })
                    except: pass

            anomaly_input = {
                "date": rec["date"], "heure": rec["heure"],
                "rpm": float(rpm) if rpm else None,
                "voltage": float(voltage) if voltage else None,
                "power_kw": float(power) if power else None,
            }
            anomaly_output = {
                "task": "anomaly_detection",
                "timestamp": f"{rec['date']} {rec['heure']}",
                "anomalies_found": len(anomalies),
                "anomalies": anomalies if anomalies else [],
                "status": "anomaly_detected" if anomalies else "normal"
            }
            training_examples.append({
                "text": f"<|im_start|>user\nAnalyze these readings for anomalies:\n{json.dumps(anomaly_input, ensure_ascii=False)}<|im_end|>\n<|im_start|>assistant\n{json.dumps(anomaly_output, ensure_ascii=False)}<|im_end|>"
            })

        json_path = os.path.join(output_path, filename.replace('.xlsx', '.json'))
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(training_examples, f, ensure_ascii=False, indent=2, default=str)

        print(f"✅ {filename}: {len(training_examples)} training examples")

    except Exception as e:
        print(f"❌ {filename}: {e}")

print("\n--- Done ---")

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
from peft import LoraConfig, get_peft_model
from trl import SFTTrainer
from datasets import load_dataset

model_id = "LiquidAI/LFM2.5-1.2B-Instruct"

# 1. Quantization Config (makes it fit on Colab T4)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

# 2. Load Tokenizer & Model
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token # Essential for training

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

# 3. Setup LoRA (Fine-tuning "Adapters")
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"], # Standard targets
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)

import json, glob, os
from datasets import Dataset

json_folder = "/content/converted_json/"
json_files = glob.glob(os.path.join(json_folder, "*.json"))

all_examples = []
for filepath in json_files:
    with open(filepath, "r", encoding="utf-8") as f:
        examples = json.load(f)
    all_examples.extend(examples)
    print(f"✅ {os.path.basename(filepath)}: {len(examples)} examples")

print(f"\n✅ Total training examples: {len(all_examples)}")
print(f"\nSample:\n{all_examples[0]['text'][:300]}")

import trl
print("trl version:", trl.__version__)

# Check what SFTConfig actually accepts
import inspect
from trl import SFTConfig
sig = inspect.signature(SFTConfig.__init__)
print("\nSFTConfig parameters:")
for name, param in sig.parameters.items():
    print(f"  {name}: {param.default}")

from trl import SFTTrainer, SFTConfig
from datasets import Dataset

dataset = Dataset.from_list(all_examples)

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    args=SFTConfig(
        max_length=2048,
        packing=False,
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=50,
        max_steps=1000,
        learning_rate=2e-4,
        fp16=True,
        logging_steps=50,
        output_dir="outputs",
        optim="paged_adamw_32bit",
        save_strategy="no",
        report_to="none"
    ),
)

trainer.train()

import shutil

save_dir = "/content/fine_tuned_model"

# Save LoRA adapter + tokenizer
model.save_pretrained(save_dir)
tokenizer.save_pretrained(save_dir)
print("✅ Model saved!")

# Also save a model card
model_card = """# Fine-tuned LFM2.5-1.2B — Energy & CO2 Analysis

## Base model
LiquidAI/LFM2.5-1.2B-Instruct

## Fine-tuning
- Method: QLoRA (4-bit quantization + LoRA adapters)
- Tasks: CO2 estimation, energy forecasting, anomaly detection
- Data: Industrial gas engine monitoring reports (monthly XLSX)

## Tasks supported
- `co2_estimation` — estimates CO2 emissions from gas consumption delta
- `energy_forecasting` — predicts next power reading from 5-step window
- `anomaly_detection` — detects spikes, out-of-range, voltage anomalies

## Input/Output format
JSON in, JSON out. See README for prompt format.
"""

with open(f"{save_dir}/README.md", "w") as f:
    f.write(model_card)

# Zip for download
shutil.make_archive("/content/fine_tuned_model", 'zip', save_dir)
print("✅ Zipped: /content/fine_tuned_model.zip")
print("📥 Download it from the Files panel on the left (folder icon)")