# -*- coding: utf-8 -*-
"""data_cleaning nrtf

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VLRQgz-E7p_h85zcoVIa-y244guGK1Eh
"""

!pip install easyocr opencv-python-headless pandas numpy matplotlib openpyxl pymupdf

import os
import re
import cv2
import fitz
import numpy as np
import pandas as pd
import easyocr
from pathlib import Path
import matplotlib.pyplot as plt

# 3. CONFIG
INPUT_DIR = "/content/input_files"
OUTPUT_DIR = "/content/output"

os.makedirs(INPUT_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

reader = easyocr.Reader(['ar', 'en'], gpu=False)

# 4. IMAGE PREPROCESSING
# =========================
def preprocess_image(image_path):
    img = cv2.imread(str(image_path))

    if img is None:
        raise ValueError(f"Cannot read image: {image_path}")

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Increase resolution
    gray = cv2.resize(gray, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)

    # Denoise
    denoised = cv2.fastNlMeansDenoising(gray, None, 30, 7, 21)

    # Improve contrast
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    contrast = clahe.apply(denoised)

    # Binarization
    thresh = cv2.adaptiveThreshold(
        contrast,
        255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY,
        31,
        15
    )

    return thresh

# 5. PDF TO IMAGES

def pdf_to_images(pdf_path):
    images = []
    doc = fitz.open(pdf_path)

    for page_num in range(len(doc)):
        page = doc[page_num]
        pix = page.get_pixmap(matrix=fitz.Matrix(2, 2))
        img_path = f"{OUTPUT_DIR}/{Path(pdf_path).stem}_page_{page_num+1}.png"
        pix.save(img_path)
        images.append(img_path)

    return images

# 6. OCR FUNCTION

def run_ocr_on_image(image_path):
    processed = preprocess_image(image_path)

    processed_path = f"{OUTPUT_DIR}/processed_{Path(image_path).stem}.png"
    cv2.imwrite(processed_path, processed)

    results = reader.readtext(processed)

    extracted_lines = []
    for bbox, text, confidence in results:
        extracted_lines.append({
            "text": text,
            "confidence": confidence
        })

    return extracted_lines

# 7. FIELD EXTRACTION
def clean_number(value):
    value = value.replace(" ", "")
    value = value.replace(",", ".")
    value = re.sub(r"[^0-9.]", "", value)

    try:
        return float(value)
    except:
        return None


def extract_fields(raw_text):
    text = raw_text.lower()

    # Date patterns
    date_pattern = r"(\d{1,2}[/-]\d{1,2}[/-]\d{2,4})"
    dates = re.findall(date_pattern, raw_text)

    # Energy units
    unit_pattern = r"(kwh|kw h|mwh|gcal|btu|toe|gj|nm3|m3)"

    # Number followed by unit
    quantity_pattern = r"([0-9]+(?:[.,][0-9]+)?)\s*(kwh|kw h|mwh|gcal|btu|toe|gj|nm3|m3)"
    quantities = re.findall(quantity_pattern, text)

    extracted_values = []

    for value, unit in quantities:
        extracted_values.append({
            "energy_quantity": clean_number(value),
            "unit": unit.replace("kw h", "kwh")
        })

    # Supplier guess
    supplier_keywords = ["steg", "sonede", "gaz", "electricite", "electricité", "électricité"]
    supplier = None

    for keyword in supplier_keywords:
        if keyword in text:
            supplier = keyword.upper()
            break

    return {
        "date": dates[0] if dates else None,
        "supplier": supplier,
        "values": extracted_values
    }

# 8. UNIT NORMALIZATION TO kWh
CONVERSION_TO_KWH = {
    "kwh": 1,
    "mwh": 1000,
    "gj": 277.777778,
    "gcal": 1162.22222,
    "btu": 0.000293071,
    "toe": 11630,
    # Approximate conversion for natural gas.
    # You can change this if organizers give another factor.
    "nm3": 10.55,
    "m3": 10.55
}

def convert_to_kwh(value, unit):
    unit = unit.lower().strip()

    if value is None or unit not in CONVERSION_TO_KWH:
        return None

    return value * CONVERSION_TO_KWH[unit]

# 9. PROCESS ONE FILE
def process_file(file_path):
    file_path = Path(file_path)
    records = []

    if file_path.suffix.lower() == ".pdf":
        image_paths = pdf_to_images(str(file_path))
    elif file_path.suffix.lower() in [".jpg", ".jpeg", ".png", ".webp"]:
        image_paths = [str(file_path)]
    else:
        return records

    for image_path in image_paths:
        ocr_lines = run_ocr_on_image(image_path)

        raw_text = "\n".join([line["text"] for line in ocr_lines])
        avg_confidence = np.mean([line["confidence"] for line in ocr_lines]) if ocr_lines else 0

        fields = extract_fields(raw_text)

        for value_data in fields["values"]:
            quantity = value_data["energy_quantity"]
            unit = value_data["unit"]
            quantity_kwh = convert_to_kwh(quantity, unit)

            records.append({
                "source_file": file_path.name,
                "date": fields["date"],
                "supplier": fields["supplier"],
                "energy_quantity_original": quantity,
                "original_unit": unit,
                "energy_kwh": quantity_kwh,
                "ocr_confidence": avg_confidence,
                "raw_text": raw_text
            })

    return records

# 10. PROCESS EXCEL FILES
# =========================
def process_excel(file_path):
    records = []

    xls = pd.ExcelFile(file_path)

    for sheet in xls.sheet_names:
        df = pd.read_excel(file_path, sheet_name=sheet)

        for col in df.columns:
            col_lower = str(col).lower()

            if any(unit in col_lower for unit in CONVERSION_TO_KWH.keys()):
                detected_unit = None

                for unit in CONVERSION_TO_KWH.keys():
                    if unit in col_lower:
                        detected_unit = unit
                        break

                for idx, value in df[col].dropna().items():
                    value_clean = clean_number(str(value))
                    records.append({
                        "source_file": Path(file_path).name,
                        "sheet": sheet,
                        "date": None,
                        "supplier": None,
                        "energy_quantity_original": value_clean,
                        "original_unit": detected_unit,
                        "energy_kwh": convert_to_kwh(value_clean, detected_unit),
                        "ocr_confidence": None,
                        "raw_text": None
                    })

    return records

print(os.listdir("/content/input_files"))
print(df.shape)

# 11. RUN FULL PIPELINE
all_records = []

for file in Path(INPUT_DIR).iterdir():
    suffix = file.suffix.lower()

    print("Processing:", file.name)

    if suffix in [".jpg", ".jpeg", ".png", ".webp", ".pdf"]:
        all_records.extend(process_file(file))

    elif suffix in [".xlsx", ".xls"]:
        all_records.extend(process_excel(file))

df = pd.DataFrame(all_records)

df.to_csv(f"{OUTPUT_DIR}/cleaned_energy_data.csv", index=False)

df.head()

# 13. SIMPLE ANOMALY DETECTION
# =========================
def detect_anomalies(df):
    df = df.copy()
    if "energy_kwh" not in df.columns or df.empty:
    print("Warning: no energy_kwh data to analyze.")
    return df
    df["anomaly_type"] = None
    df["anomaly_confidence"] = 0.0

    values = df["energy_kwh"].dropna()

    if len(values) < 5:
        return df

    mean = values.mean()
    std = values.std()
    if pd.isnull(std) or std == 0:
    return df

    for idx, row in df.iterrows():
        value = row["energy_kwh"]

        if pd.isnull(value):
            df.loc[idx, "anomaly_type"] = "missing_value"
            df.loc[idx, "anomaly_confidence"] = 0.7

        elif abs(value - mean) > 3 * std:
            df.loc[idx, "anomaly_type"] = "energy_spike"
            df.loc[idx, "anomaly_confidence"] = 0.9

    return df

df_anomaly = detect_anomalies(df)

df_anomaly.to_csv(f"{OUTPUT_DIR}/final_cleaned_energy_dataset.csv", index=False)

df_anomaly.head()

# 14. DOWNLOAD OUTPUT
# =========================
from google.colab import files

files.download(f"{OUTPUT_DIR}/final_cleaned_energy_dataset.csv")